version: "3.9"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  dnsman:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATASOURCES_DEFAULT_URL=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
      - DATASOURCES_DEFAULT_USERNAME=${POSTGRES_USER}
      - DATASOURCES_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
      - R2DBC_DATASOURCES_DEFAULT_URL=r2dbc:postgresql://localhost:5432/${POSTGRES_DB}
      - R2DBC_DATASOURCES_DEFAULT_USERNAME=${POSTGRES_USER}
      - R2DBC_DATASOURCES_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
