micronaut:
  application:
    name: dnsman
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
  server:
    dns:
      port: 1053
#otel:
#  traces:
#    exporter: jaeger

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
r2dbc:
  datasources:
    default:
      dialect: POSTGRES
      db-type: postgres
flyway:
  datasources:
    default:
      enabled: true
