[versions]
micronaut = "4.0.2"
reactor = "3.5.8"
junit = "5.10.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.28" }
jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version = "2.0.1" }
reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "reactor" }
reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactor" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.4.0" }
micronaut-security-aot = { module = "io.micronaut.security:micronaut-security-aot", version = "4.0.1" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut" }
micronaut-library = { id = "io.micronaut.library", version.ref = "micronaut" }
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronaut" }
